const Goods = [
    {
        id: '1',
        typeName: "创世系列",
        collections: [
            {
                img_id: '1',
                imageName: '红色的鹦鹉',
                abstract: '这是红色的鹦鹉的一段简介',
                nums:5,
                url: "https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg",
            },
            {
                img_id: '2',
                imageName: '夕阳照射的山峰',
                abstract: '这是夕阳照射的山峰的一段简介',
                nums: 1,
                url: "https://cube.elemecdn.com/6/94/4d3ea53c084bad6931a56d5158a48jpeg.jpeg",
            },
            {
                img_id: '3',
                imageName: '好奇的小鹿',
                abstract: '这是好奇的小鹿的一段简介',
                nums: 25,
                url: "https://fuss10.elemecdn.com/a/3f/3302e58f9a181d2509f3dc0fa68b0jpeg.jpeg",
            },
            {
                img_id: '4',
                imageName: '庄严的骏马',
                abstract: '这是庄严的骏马的一段简介',
                nums: 21,
                url: "https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg",
            },
        ],
    },
    {
        id: '2',
        typeName: "永乐宫系列",
        collections: [
            {
                img_id: '5',
                imageName: '压迫感',
                abstract: '这是压迫感的一段简介',
                nums: 15,
                url: "https://fuss10.elemecdn.com/0/6f/e35ff375812e6b0020b6b4e8f9583jpeg.jpeg",
            },
            {
                img_id: '6',
                imageName: '雪花',
                abstract: '这是雪花的一段简介',
                nums: 7,
                url: "https://fuss10.elemecdn.com/9/bb/e27858e973f5d7d3904835f46abbdjpeg.jpeg",
            },
            {
                img_id: '7',
                imageName: '狐狸高清头像',
                abstract: '这是狐狸高清头像的一段简介',
                nums: 2,
                url: "https://fuss10.elemecdn.com/d/e6/c4d93a3805b3ce3f323f7974e6f78jpeg.jpeg",
            },
            {
                img_id: '8',
                imageName: '阳光下的雪狐',
                abstract: '这是阳光下的雪狐的一段简介',
                nums: 3,
                url: "https://fuss10.elemecdn.com/3/28/bbf893f792f03a54408b3b7a7ebf0jpeg.jpeg",
            },
            {
                img_id: '9',
                imageName: '一只发呆的猴子',
                abstract: '这是一只发呆的猴子的一段简介',
                nums: 32,
                url: "https://fuss10.elemecdn.com/2/11/6535bcfb26e4c79b48ddde44f4b6fjpeg.jpeg",
            },
        ],
    },
    {
        id: '1',
        typeName: "创世系列2",
        collections: [
            {
                img_id: '1',
                imageName: '红色的鹦鹉',
                abstract: '这是红色的鹦鹉的一段简介',
                nums: 5,
                url: "https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg",
            },
            {
                img_id: '2',
                imageName: '夕阳照射的山峰',
                abstract: '这是夕阳照射的山峰的一段简介',
                nums: 1,
                url: "https://cube.elemecdn.com/6/94/4d3ea53c084bad6931a56d5158a48jpeg.jpeg",
            },
            {
                img_id: '3',
                imageName: '好奇的小鹿',
                abstract: '这是好奇的小鹿的一段简介',
                nums: 25,
                url: "https://fuss10.elemecdn.com/a/3f/3302e58f9a181d2509f3dc0fa68b0jpeg.jpeg",
            },
            {
                img_id: '4',
                imageName: '庄严的骏马',
                abstract: '这是庄严的骏马的一段简介',
                nums: 21,
                url: "https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg",
            },
        ],
    },
    {
        id: '2',
        typeName: "永乐宫系列2",
        collections: [
            {
                img_id: '5',
                imageName: '压迫感',
                abstract: '这是压迫感的一段简介',
                nums: 15,
                url: "https://fuss10.elemecdn.com/0/6f/e35ff375812e6b0020b6b4e8f9583jpeg.jpeg",
            },
            {
                img_id: '6',
                imageName: '雪花',
                abstract: '这是雪花的一段简介',
                nums: 7,
                url: "https://fuss10.elemecdn.com/9/bb/e27858e973f5d7d3904835f46abbdjpeg.jpeg",
            },
            {
                img_id: '7',
                imageName: '狐狸高清头像',
                abstract: '这是狐狸高清头像的一段简介',
                nums: 2,
                url: "https://fuss10.elemecdn.com/d/e6/c4d93a3805b3ce3f323f7974e6f78jpeg.jpeg",
            },
            {
                img_id: '8',
                imageName: '阳光下的雪狐',
                abstract: '这是阳光下的雪狐的一段简介',
                nums: 3,
                url: "https://fuss10.elemecdn.com/3/28/bbf893f792f03a54408b3b7a7ebf0jpeg.jpeg",
            },
            {
                img_id: '9',
                imageName: '一只发呆的猴子',
                abstract: '这是一只发呆的猴子的一段简介',
                nums: 32,
                url: "https://fuss10.elemecdn.com/2/11/6535bcfb26e4c79b48ddde44f4b6fjpeg.jpeg",
            },
        ],
    },
    {
        id: '3',
        typeName: "创世系列2",
        collections: [
            {
                img_id: '1',
                imageName: '红色的鹦鹉',
                abstract: '这是红色的鹦鹉的一段简介',
                nums: 5,
                url: "https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg",
            },
            {
                img_id: '2',
                imageName: '夕阳照射的山峰',
                abstract: '这是夕阳照射的山峰的一段简介',
                nums: 1,
                url: "https://cube.elemecdn.com/6/94/4d3ea53c084bad6931a56d5158a48jpeg.jpeg",
            },
            {
                img_id: '3',
                imageName: '好奇的小鹿',
                abstract: '这是好奇的小鹿的一段简介',
                nums: 25,
                url: "https://fuss10.elemecdn.com/a/3f/3302e58f9a181d2509f3dc0fa68b0jpeg.jpeg",
            },
            {
                img_id: '4',
                imageName: '庄严的骏马',
                abstract: '这是庄严的骏马的一段简介',
                nums: 21,
                url: "https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg",
            },
        ],
    },
];

export default Goods
